src/EFCoreToDo/Models/Mark.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EFCoreToDo.Models
{
   public class Mark
    {
        [Key]
        public int MarkId { get; set; }
        public float CC { get; set; }
        public float DS { get; set; }
        public float Exam { get; set; }

        public float Moyenne { get; set; }

        //Relation with "Module" class
        public virtual Module Modulee { get; set; }

        //Relation with "Student" class
        public virtual Student sutdents { get; set; }


    }
}

src/EFCoreToDo/Controllers/MarkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EFCoreToDo.Models;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.Rendering;
using static Microsoft.AspNetCore.Hosting.Internal.HostingApplication;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace EFCoreToDo.Controllers
{
    public class MarkController : Controller
    {
        private readonly ToDoDbContext _context;
        public MarkController(ToDoDbContext context)
        {
            _context = context;
        }

    

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult AddMark()
        {
            return View();
        }



        [HttpGet]
        public async Task<IActionResult> MarkList()
        {

            IEnumerable<Mark> markAll = _context.Marks.ToList();

            try
            {
                //WebService Json Format .
                await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(markAll); });

                //List to The view

                return View(await _context.Marks.ToListAsync());

            }
            catch (Exception e)
            {
                return RedirectToAction("Error", e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddMark(Mark mark)
        {
            try
            {
                _context.Marks.Add(mark);
                await _context.SaveChangesAsync();
                await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(mark); });
                return RedirectToAction("MarkList");

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return RedirectToAction("MarkList");
            }
        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var MArks = await _context.Marks.SingleOrDefaultAsync(m => m.MarkId == id);
            if (MArks == null)
            {
                return NotFound();
            }
            return View(MArks);
        }

        // POST: Module/Edit/5 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MarkId,CC,DS,Exam")] Mark Mar)
        {
            if (id != Mar.MarkId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {


                _context.Update(Mar);
                await _context.SaveChangesAsync();


                return RedirectToAction("MarkList");
            }
            return View(Mar);
        }



        public async Task<IActionResult> Delete(int? id)
        {


            var MarkSelected = await _context.Marks.SingleOrDefaultAsync(m => m.MarkId == id);
            if (MarkSelected == null)
            {
                return RedirectToAction("Error");
            }

            return View(MarkSelected);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var MarkSelected = await _context.Marks.SingleOrDefaultAsync(m => m.MarkId == id);
            _context.Marks.Remove(MarkSelected);
            await _context.SaveChangesAsync();
            return RedirectToAction("MarkList");
        }


        //---------------Web Service (WebApi)-----------

        [HttpGet]
        public async Task<dynamic> GetAllapiMark()
        {
            try
            {
                var MARKList = _context.Marks.ToList();
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(MARKList); });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to GET. Stack Trace: " + ex.StackTrace;
                Console.WriteLine(errorMessage);
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(new { msg = errorMessage }); });
            }
            

        }

        //[HttpPost]
        //public async Task<dynamic> CreateApi(Mark mrk)
        //{
        //    try
        //    {
        //        _context.Marks.Add(mrk);
        //        await _context.SaveChangesAsync();
        //        return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(mrk); });
        //    }
        //    catch (Exception ex)
        //    {
        //        var errorMessage = "Failure to POST. Stack Trace: " + ex.StackTrace;
        //        Console.WriteLine(errorMessage);
        //        return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(new { msg = errorMessage }); });
        //    }
        //}

        //[Route("api/ProductController")]
        [HttpPost]
        public IActionResult Createapi([FromBody] Mark mark)
        {

            if (mark == null)
            {
                return BadRequest();
            }
            
            _context.Add(mark);

            return new ObjectResult("ok");
        }
    }

    //[HttpPost]
    //public async Task<dynamic> CreateApiNote([FromBody]Mark markk)
    //{
    //    try
    //    {
            
    //        _context.Marks.Add(markk);
    //        await Context.SaveChangesAsync();
    //        return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(markk); });
    //    }
    //    catch (Exception ex)
    //    {
    //        var errorMessage = "Failure to POST. Stack Trace: " + ex.StackTrace;
    //        Console.WriteLine(errorMessage);
    //        return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(new { msg = errorMessage }); });
    //    }
    //}




}
    

src/EFCoreToDo/Views/Mark/AddMark.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    ViewBag.Title = "Add Mark";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model EFCoreToDo.Models.Mark

@{
    ViewBag.Title = "ADD MARK";
}

<h2>Add MARK</h2>

<!-- html helper -->
@using (Html.BeginForm("AddMark", "Mark"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.MarkId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarkId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarkId, "", new { @class = "text-danger" })
            </div>
        </div*@>

        <div class="form-group">
            @Html.LabelFor(model => model.CC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Exam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Exam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Exam, "", new { @class = "text-danger" })
            </div>
        </div>
        




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="AddMark" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Go Back ", "MarkList")
</div>

src/EFCoreToDo/Views/Mark/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewBag.Title = "Delete wrong mark";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EFCoreToDo.Models.Mark

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Mark </h2>

<form asp-action="Delete">
    <input type="hidden" asp-for="MarkId" />
    <div class="form-horizontal">
        <div class="form-group">
            <label>Please confirm to delete Mark</label>
            <div class="col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
                <a asp-action="Index" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>

src/EFCoreToDo/Views/Mark/Edit.cshtml
@{
    ViewBag.Title = "Edit Mark";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EFCoreToDo.Models.Mark

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Mark</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Mark</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="MarkId" />
        <div class="form-group">
            <label asp-for="CC" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CC" class="form-control" />
                <span asp-validation-for="CC" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DS" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DS" class="form-control" />
                <span asp-validation-for="DS" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Exam" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Exam" class="form-control" />
                <span asp-validation-for="Exam" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/EFCoreToDo/Views/Mark/MarkList.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    ViewBag.Title = "GetMarks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<EFCoreToDo.Models.Mark>





@*<!DOCTYPE html>*@

@*<hml>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
    </head>*@
@*<body>*@



<style>
    body
    {font-family:sans-serif;
     font-size:11pt;
     background-image:url(images/3.jpg);
     background-size:cover;
     background-attachment:fixed;

    }
    table 
    {
        width:80%;

    }
    table,th,td 
    {
    border:1px solid black;
    border-collapse:collapse;
    opacity:0.95;
    }
    th,td
    {
        padding:10px;
        text-align:center;
    }
    th
    { background-color:#5c0707;
      color:white;
    }
    tr:nth-child(even)
    {
        background-color:#e8e8e8;
    }

     tr:nth-child(old)
    {
        background-color:white;
    }

    #header
     {
        background-color:#89bcbf;
        color:white;

     }
</style>

<body>
    <table align="center">
        <div class="post">
            <thead>
                <tr>
                    <td id="header" colspan="7"><h1> students marks </h1></td>
                </tr>

                <tr>
                    <th>  CC </th>
                    <th>  DS </th>
                    <th>  Exam  </th>
                    <th>  Moyenne </th>



                </tr>
            </thead>

         
        </div>

        @foreach (var Markitem in Model)
        {

            
            <tbody>
                <tr>
                    <td>@Html.DisplayFor(mark => Markitem.CC)</td>
                    <td>@Html.DisplayFor(mark => Markitem.DS)</td>
                    <td>@Html.DisplayFor(mark => Markitem.Exam)</td>
                    <td>@Html.DisplayFor(mark => Markitem.Moyenne)</td>
                    <td> <a asp-action="Edit" asp-route-id="@Markitem.MarkId">Edit</a></td>
                    <td> <a asp-action="Delete" asp-route-id="@Markitem.MarkId">Delete</a></td>

                </tr>

            </tbody>

        }
        @*<div>
                @RenderBody()
            </div>*@
        @*</body>
            </hml>*@
    </table>
</body>