src/EFCoreToDo/Models/Homework.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EFCoreToDo.Models
{
  public  class Homework
    {
        [Key]
        public int HomeworkId { get; set; }
        public String Label { get; set; }

        [DataType(DataType.MultilineText)]

        public String HomeworkDescription { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime DateLimit { get; set; }
        public String difficulty { get; set; }

        [ForeignKey("Modulee")]
        public Nullable<int> idmodule { get; set; }

        //Relation with "Module" class
        public virtual Module Modulee { get; set; }


    }
}

src/EFCoreToDo/Controllers/HomeworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EFCoreToDo.Models;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Cors;


// For more information on enabling MVC for empty prrojects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace EFCoreToDo.Controllers
{
    [EnableCors("CorsPolicy")]
    public class HomeworkController : Controller
    {
        private readonly ToDoDbContext _context;

        public HomeworkController(ToDoDbContext context)
        {
            _context = context;
        }


        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }




        // GET: /<controller>/
        public IActionResult Create()
        {

            // -- liste des modules : pour les envoyer au view 
            // -- de creation d'un Homework

            IEnumerable<Module> modules = _context.Modules.ToList();

            // ---- ici on va prendre la valeur de L'id on affichant
            // ---- le Nom du module (dans le formulaire)

            ViewBag.modules = new SelectList(modules, "ModuleId", "ModuleName");

            return View();
        }




        //[HttpPost]
        //public async Task<IActionResult> Create(Homework homwrkk)
        //{
        //    try
        //    {

        //        _context.Homeworks.Add(homwrkk);
        //        await _context.SaveChangesAsync();
        //        await Task.Factory.StartNew(() => {
        //            _context.Homeworks.Add(homwrkk);
        //            return JsonConvert.SerializeObject(homwrkk);
        //        });
        //        return RedirectToAction("GetAll");

        //    }
        //    catch (Exception ex)
        //    {
        //        Console.WriteLine(ex);
        //        return RedirectToAction("Create");
        //    }
        //}

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            try
            {
                //List to The view
                return View(await _context.Homeworks.ToListAsync());
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            // -- liste des modules : pour les envoyer au view 
            // -- de creation d'un Homework

            IEnumerable<Module> modules = _context.Modules.ToList();

            // ---- ici on va prendre la valeur de L'id on affichant
            // ---- le Nom du module (dans le formulaire)

            ViewBag.modules = new SelectList(modules, "ModuleId", "ModuleName");

            var HomeWrkk = await _context.Homeworks.SingleOrDefaultAsync(m => m.HomeworkId == id);
            if (HomeWrkk == null)
            {
                return NotFound();
            }
            return View(HomeWrkk);
        }

        // POST: Homework/Edit/5 




        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HomeworkId,HomeworkDescription,DateLimit,difficulty,Label,idmodule")] Homework homwrk)
        {
            if (id != homwrk.HomeworkId)
            {
                return RedirectToAction("Error");
            }

            if (ModelState.IsValid)
            {
                _context.Update(homwrk);
                await _context.SaveChangesAsync();
                return RedirectToAction("GetAll");
            }
            return View(homwrk);
        }



        public async Task<IActionResult> Delete(int? id)
        {


            var HomeworkSelectionne = await _context.Homeworks.SingleOrDefaultAsync(m => m.HomeworkId == id);
            if (HomeworkSelectionne == null)
            {
                return RedirectToAction("Error");
            }

            return View(HomeworkSelectionne);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var HomeworkSelectionne = await _context.Homeworks.SingleOrDefaultAsync(m => m.HomeworkId == id);
            _context.Homeworks.Remove(HomeworkSelectionne);
            await _context.SaveChangesAsync();
            return RedirectToAction("GetAll");
        }



        public string GetNameModuleById(int id)

        {
            string resut = "";
            IEnumerable<Module> modules = _context.Modules.ToList();
            foreach (var item in modules)
            {
                if (item.ModuleId == id)
                {
                    resut = item.ModuleName;
                }
            }
            return resut;
        }

        public int GetNumberHomeworkByModule(int idMod)
        {
            int result = 0;
            IEnumerable<Homework> allHomwrk = _context.Homeworks.ToList();


            foreach (var item in allHomwrk)
            {
                if (item.idmodule == idMod)
                {
                    result = result + 1;
                }
            }

            return result;
        }


        //**** statistique *****
        [HttpGet]
        public async Task<IActionResult> HomeworkmoduleStat()
        {
            List<Module> modules = await _context.Modules.ToListAsync();

            List<string> NameModule = new List<string> { };
            List<int> NombreHomework = new List<int> { };

            //NameModule.Add("A");
            //NameModule.Add("B");

            //NombreHomework.Add(2);
            //NombreHomework.Add(3);

            //--- remplissage des 2 list :
            // -- list1 : NameModule --> contient la liste des noms des modules
            // -- list2 : NombreHomework --> Contient le nombre de homework de chaque modules
            foreach (var item in modules)
            {
                NameModule.Add(item.ModuleName);
                NombreHomework.Add(GetNumberHomeworkByModule(item.ModuleId));
            }



            // convert it in json
            string dataNameModule = JsonConvert.SerializeObject(NameModule, Formatting.None);
            string dataNombreHomework = JsonConvert.SerializeObject(NombreHomework, Formatting.None);
            // store it in viewdata/ viewbag
            ViewBag.dataNameModule = new HtmlString(dataNameModule);
            ViewBag.dataNombreHomework = new HtmlString(dataNombreHomework);



            return View();
        }


        //***************** RESTful webService **********************************************

        //***********************************************************************************
        [HttpGet]
        public async Task<dynamic> GetAllapi()
        {
            try
            {
                var HomeworkAlll = _context.Homeworks.ToList();
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(HomeworkAlll); });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to GET. Stack Trace: " + ex.StackTrace;
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(new { msg = errorMessage }); });
            }
        }
        //***********************************************************************************

        [HttpGet]
        public async Task<dynamic> ListeHomeworkByModulApi([FromBody]int? id)
        {


            List<Homework> AllModules = await _context.Homeworks.ToListAsync();
            List<Homework> Homworkfiltree = new List<Homework> { };

            foreach (var item in AllModules)
            {
                if (item.idmodule == id)
                {
                    Homworkfiltree.Add(item);
                }

            }

            try
            {

                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(Homworkfiltree); });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to GET. Stack Trace: " + ex.StackTrace;
                Console.WriteLine(errorMessage);
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(new { msg = errorMessage }); });
            }
        }


        //***********************************************************************************

        [HttpDelete("{id}")]
        public IActionResult DeleteApi([FromBody]int id)
        {
            var homewrk = _context.Homeworks.SingleOrDefault(x => x.HomeworkId == id);
            if (homewrk == null)
            {
                return NotFound();
            }
            _context.Homeworks.Remove(homewrk);

            return NoContent();
        }


        //***********************************************************************************

        [HttpPost]
        public async Task<dynamic> Create([FromBody]Homework hmrk)
        {
            try
            {
                _context.Homeworks.Add(hmrk);
                await _context.SaveChangesAsync();
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(hmrk); });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to POST. Stack Trace: " + ex.StackTrace;
                Console.WriteLine(errorMessage);
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(new { msg = errorMessage }); });
            }
        }

        //***********************************************************************************

        [HttpPut]
        public async Task<string> EditApi([FromBody]Homework item)
        {
            try
            {

src/EFCoreToDo/Views/Homework/Create.cshtml
@{
    ViewBag.Title = "Create HomeWork";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EFCoreToDo.Models.Homework

@{
    ViewBag.Title = "CreateHomework";
}

<h2>Create Homework</h2>

<!-- html helper -->
@using (Html.BeginForm("Create", "Homework"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Homework</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Label, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Label, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.difficulty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.difficulty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.difficulty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeworkDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeworkDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeworkDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateLimit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateLimit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateLimit, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.idmodule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idmodule, (SelectList)ViewData["modules"], new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idmodule)
            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetAll")
</div>

@*-By-Wissem-*@

src/EFCoreToDo/Views/Homework/Delete.cshtml
@{
    ViewBag.Title = "Delete a Homework";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EFCoreToDo.Models.Homework

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Homework </h2>

<form asp-action="Delete">
    <input type="hidden" asp-for="HomeworkId" />
    <div class="form-horizontal">
        <div class="form-group">
            <label>Please confirm to delete Homework</label>
            <div class="col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
                <a asp-action="Index" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>






@*-By-Wissem-*@

src/EFCoreToDo/Views/Homework/Edit.cshtml
@{
    ViewBag.Title = "Edit a Homework";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EFCoreToDo.Models.Homework

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Homework</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="HomeworkId" />

        <div class="form-group">
            <label asp-for="Label" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Label" class="form-control" />
                <span asp-validation-for="Label" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="difficulty" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="difficulty" class="form-control" />
                <span asp-validation-for="difficulty" class="text-danger"></span>
            </div>
        </div>



        <div class="form-group">
            <label asp-for="HomeworkDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="HomeworkDescription" class="form-control" />
                <span asp-validation-for="HomeworkDescription" class="text-danger"></span>
            </div>
        </div>



        <div class="form-group">
            <label asp-for="DateLimit" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DateLimit" class="form-control" />
                <span asp-validation-for="DateLimit" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idmodule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idmodule, (SelectList)ViewData["modules"], new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idmodule)
            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>


    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>








@*-By-Wissem-*@

src/EFCoreToDo/Views/Homework/GetAll.cshtml
<!-- Bootstrap core CSS -->
<link href="~/css/bootstrap.min.css" rel="stylesheet">
<link href="~/css/bootstrap-reset.css" rel="stylesheet">

<!--Animation css-->
<link href="~/css/animate.css" rel="stylesheet">

<!--Icon-fonts css-->
<link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link href="~/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
<link href="~/assets/material-design-iconic-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

<!-- Custom styles for this template -->
<link href="~/css/style.css" rel="stylesheet">
<link href="~/css/helper.css" rel="stylesheet">




<script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-62751496-1', 'auto');
          ga('send', 'pageview');

</script>




@{
    ViewBag.Title = "List of Homework ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<EFCoreToDo.Models.Homework>





<div class="row">
    <div class="col-sm-12">
        <ul class="timeline m-b-30">


            @foreach (var HomworkItem in Model)
    {

                @if ((HomworkItem.HomeworkId == 12)||            (HomworkItem.HomeworkId == 52) ||            (HomworkItem.HomeworkId == 14) ||             (HomworkItem.HomeworkId == 16) ||             (HomworkItem.HomeworkId == 18) ||             (HomworkItem.HomeworkId == 19) ||             (HomworkItem.HomeworkId == 22) ||             (HomworkItem.HomeworkId == 23) ||             (HomworkItem.HomeworkId == 24) ||
            (HomworkItem.HomeworkId == 26) ||             (HomworkItem.HomeworkId == 28) ||             (HomworkItem.HomeworkId == 29) ||             (HomworkItem.HomeworkId == 31) ||             (HomworkItem.HomeworkId == 33) ||             (HomworkItem.HomeworkId == 34) ||
            (HomworkItem.HomeworkId == 36) ||             (HomworkItem.HomeworkId == 37) ||             (HomworkItem.HomeworkId == 38) ||
            (HomworkItem.HomeworkId == 39) ||             (HomworkItem.HomeworkId == 40) ||             (HomworkItem.HomeworkId == 45) ||             (HomworkItem.HomeworkId == 42) ||
            (HomworkItem.HomeworkId == 43) ||             (HomworkItem.HomeworkId == 46) ||             (HomworkItem.HomeworkId == 48) ||             (HomworkItem.HomeworkId == 49) ||
            (HomworkItem.HomeworkId == 50) ||             (HomworkItem.HomeworkId == 52) ||            (HomworkItem.HomeworkId == 53) ||             (HomworkItem.HomeworkId == 55))
        {



                    <li>
                        <div class="timeline-badge danger">
                            <i class="fa fa-save"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">@Html.DisplayFor(modelItem => HomworkItem.Label)</h4>
                                <p>
                                    <small class="text-muted"><i class="fa fa-time"></i> 12/12/1992</small>
                                </p>
                            </div>
                            <div class="timeline-body">
                                <p>
                                    Difficulty : @Html.DisplayFor(modelItem => HomworkItem.difficulty)
                                    <hr>
                                    @Html.DisplayFor(modelItem => HomworkItem.HomeworkDescription)
                                    <hr>
                                    Date Limit :  @Html.DisplayFor(modelItem => HomworkItem.DateLimit)
                                </p>
                            </div>
                            <hr>
                            <div class="btn-group">
                                <a class="btn btn-info btn-rounded m-b-5" asp-action="Edit" asp-route-id="@HomworkItem.HomeworkId">Edit</a>

                            </div>
                            <div class="btn-group">
                                <a class="btn btn-info btn-rounded m-b-5" asp-action="Delete" asp-route-id="@HomworkItem.HomeworkId">Delete</a>

                            </div>

                        </div>
                    </li>

        }
        else
        {

                    <li class="timeline-inverted">
                        <div class="timeline-badge danger">
                            <i class="fa fa-save"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">@Html.DisplayFor(modelItem => HomworkItem.Label)</h4>
                                <p>
                                    <small class="text-muted"><i class="fa fa-time"></i> 12/12/1992</small>
                                </p>
                            </div>
                            <div class="timeline-body">
                                <p>
                                    Difficulty : @Html.DisplayFor(modelItem => HomworkItem.difficulty)
                                    <hr>
                                    @Html.DisplayFor(modelItem => HomworkItem.HomeworkDescription)
                                    <hr>
                                    Date Limit :  @Html.DisplayFor(modelItem => HomworkItem.DateLimit)
                                </p>
                            </div>
                            <hr>
                            <div class="btn-group">
                                <a class="btn btn-info btn-rounded m-b-5" asp-action="Edit" asp-route-id="@HomworkItem.HomeworkId">Edit</a>

                            </div>
                            <div class="btn-group">
                                <a class="btn btn-info btn-rounded m-b-5" asp-action="Delete" asp-route-id="@HomworkItem.HomeworkId">Delete</a>

                            </div>

                        </div>
                    </li>



        }


    }
            }

        </ul>
    </div>
</div>


<script src="~/js/jquery.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/pace.min.js"></script>
<script src="~/js/wow.min.js"></script>
<script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>

<script src="~/js/jquery.app.js"></script>


@*-By-Wissem-*@

src/EFCoreToDo/Views/Homework/HomeworkmoduleStat.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>


    var TNameModule = JSON.parse('@ViewBag.dataNameModule');
    var TNbreHmwrk = JSON.parse('@ViewBag.dataNombreHomework');

</script>
<script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawStuff);

      function drawStuff() {


          //var TNameModule = ["A", "B", "C", "D"];
          //var TNbreHmwrk = [8, 5, 2, 6];



          var i = 0;
          var tableau = [["Module", "Number  of homework"]];
          while (i <= TNameModule.length) {
              tableau.push([TNameModule[i],TNbreHmwrk[i]]);
              i++;
          }

          var data = new google.visualization.arrayToDataTable(tableau);



        var options = {
          title: 'Chess opening moves',
          width: 900,
          legend: { position: 'none' },
          chart: { title: 'Chess opening moves',
                   subtitle: 'popularity by percentage' },
          bars: 'horizontal', // Required for Material Bar Charts..
          axes: {
            x: {
              0: { side: 'top', label: 'HomeWork'} // Top x-axis.
            }
          },
          bar: { groupWidth: "90%" }
        };

        var chart = new google.charts.Bar(document.getElementById('top_x_div'));
        chart.draw(data, options);
      };




</script>

<div id="top_x_div" style="width: 900px; height: 500px;"></div>

src/EFCoreToDo/Views/Homework/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<li>
    @Html.ActionLink( "Add Homework. ","Create")
</li>

<li>
    @Html.ActionLink("Lisr of Homeworks. ", "GetAll")
</li>