src/EFCoreToDo/Models/Classs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EFCoreToDo.Models
{
    public class Classs
    {
        [Key]
        public int ClasssId { get; set; }


        public int NbreEtudiants { get; set; }
        public string Speciality { get; set; }

        public string ClasseName { get; set; }
        public string Level { get; set; }

        //Relation with "Student" class fef
        public virtual ICollection<Student> Students { get; set; }


        ////Relation with "Modules" class
        //public virtual ICollection<Module> Modules { get; set; }


        //Relation with "ModulsClass" classAssociation ____ many
        public virtual ICollection<ModulsClass> ModulsClasss { get; set; }

    }
}

src/EFCoreToDo/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EFCoreToDo.Models;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Cors;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace EFCoreToDo.Controllers
{
    [EnableCors("CorsPolicy")]
    public class ClassController : Controller
    {
        private readonly ToDoDbContext _context;

        public ClassController(ToDoDbContext context)
        {
            _context = context;
        }


        // GET: /<controller>/ chems

        //public IActionResult Index()
        //{
        //    return View();
        //}
        [HttpGet]

        public async Task<IActionResult> Index()
        {
            return View(await _context.Classs.ToListAsync());
        }



        // GET: /<controller>/
        public IActionResult Create()
        {
            return View();
        }


        //[HttpPost]
        //public async Task<IActionResult> Create(Classs cl)
        //{

        //    _context.Classs.Add(cl);
        //    await _context.SaveChangesAsync();
        //    await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(cl); });
        //    return RedirectToAction("Index");

        //}

      




        
        public async Task<dynamic> GetAllapi()
        {
            try
            {
                var Classes = _context.Classs.ToList();
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(Classes); });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to GET. Stack Trace: " + ex.StackTrace;
                Console.WriteLine(errorMessage);
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(new { msg = errorMessage }); });
            }
        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classes = await _context.Classs.SingleOrDefaultAsync(m => m.ClasssId == id);
            if (classes == null)
            {
                return NotFound();
            }
            return View(classes);
        }

        // POST: Students/Edit/5 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClasssId,NbreEtudiants,Speciality,ClasseName,Level")] Classs clas)
        {
            if (id != clas.ClasssId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {


                _context.Update(clas);
                await _context.SaveChangesAsync();


                return RedirectToAction("Index");
            }
            return View(clas);
        }

        public async Task<IActionResult> Delete(int? id)
        {


            var Classes = await _context.Classs.SingleOrDefaultAsync(m => m.ClasssId == id);
            if (Classes == null)
            {
                return NotFound();
            }

            return View(Classes);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var classes = await _context.Classs.SingleOrDefaultAsync(m => m.ClasssId == id);
            _context.Classs.Remove(classes);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        [HttpPut]
        public async Task<string> UpdateAPI(Classs c)
        {
            try
            {
                var dbItem = _context.Classs.FirstOrDefault(m => m.ClasssId == c.ClasssId);
                if (dbItem == null)
                {
                    return await Task.Factory.StartNew(() =>
                    {
                        return JsonConvert.SerializeObject(new { msg = "Failure to PUT.  Item not found." });
                    });
                }
                dbItem.Level = c.Level;
                dbItem.ClasseName= c.ClasseName;
                dbItem.NbreEtudiants = c.NbreEtudiants;
                dbItem.Speciality = c.Speciality;

                _context.Update(dbItem);
                await _context.SaveChangesAsync();
                return await Task.Factory.StartNew(() =>
                {
                    return JsonConvert.SerializeObject(dbItem);
                });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to PUT. Stack Trace: " + ex.StackTrace;
                Console.WriteLine(errorMessage);
                return await Task.Factory.StartNew(() =>
                {
                    return JsonConvert.SerializeObject(new { msg = errorMessage });
                });

            }

        }




        //***************** RESTful webService **********************************************

      




        //***********************************************************************************

        [HttpPost]
        public async Task<dynamic> Create([FromBody]Classs cll)
        {
            try
            {
                _context.Classs.Add(cll);
                await _context.SaveChangesAsync();
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(cll); });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to POST. Stack Trace: " + ex.StackTrace;
                Console.WriteLine(errorMessage);
                return await Task.Factory.StartNew(() => { return JsonConvert.SerializeObject(new { msg = errorMessage }); });
            }
        }

        //***********************************************************************************

        [HttpPut]
        public async Task<string> EditApi([FromBody]Classs item)
        {
            try
            {
                var dbItem = _context.Classs.FirstOrDefault(m => m.ClasssId == item.ClasssId);

                dbItem.ClasseName = item.ClasseName;
                dbItem.Level = item.Level;
                dbItem.NbreEtudiants = item.NbreEtudiants;
                dbItem.Speciality = item.Speciality;
                _context.Update(dbItem);
                await _context.SaveChangesAsync();
                return await Task.Factory.StartNew(() =>
                {
                    return JsonConvert.SerializeObject(dbItem);
                });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to PUT. Stack Trace: " + ex.StackTrace;
                Console.WriteLine(errorMessage);
                return await Task.Factory.StartNew(() =>
                {
                    return JsonConvert.SerializeObject(new { msg = errorMessage });
                });
            }
        }

        //***********************************************************************************
        [HttpDelete]
        public async Task<dynamic> DeleteApi([FromBody] Classs cl)
        {
            try
            {
                var dbItem = _context.Classs.FirstOrDefault(m => m.ClasssId == cl.ClasssId);
                if (dbItem == null)
                {
                    return await Task.Factory.StartNew(() =>
                    {
                        return JsonConvert.SerializeObject(new { msg = "Failure to DELETE.  Item not found." });
                    });
                }
                _context.Classs.Remove(dbItem);
                await _context.SaveChangesAsync();
                return await Task.Factory.StartNew(() =>
                {
                    return JsonConvert.SerializeObject(dbItem);
                });
            }
            catch (Exception ex)
            {
                var errorMessage = "Failure to DELETE. Stack Trace: " + ex.StackTrace;
                Console.WriteLine(errorMessage);
                return await Task.Factory.StartNew(() =>
                {
                    return JsonConvert.SerializeObject(new { msg = errorMessage });
                });
            }
        }



    }
}

src/EFCoreToDo/Views/Class/Create.cshtml
@{
    ViewBag.Title = "Create__Classe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EFCoreToDo.Models.Classs

@{
    ViewBag.Title = "CreateClass";
}

<h2>Create Class</h2>

<!-- html helper -->
@using (Html.BeginForm("Create", "Class"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Classe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClasseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClasseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClasseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Level, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Speciality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Speciality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Speciality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NbreEtudiants, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NbreEtudiants, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NbreEtudiants, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/EFCoreToDo/Views/Class/Delete.cshtml
@{
    ViewBag.Title = "Delete__Classe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EFCoreToDo.Models.Classs

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Classe</h2>

<form asp-action="Delete">
    <input type="hidden" asp-for="ClasssId" />
    <div class="form-horizontal">
        <div class="form-group">
            <label>Please confirm to delete Classe</label>
            <div class="col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
                <a asp-action="Index" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>

src/EFCoreToDo/Views/Class/Edit.cshtml
@{
    ViewBag.Title = "Modification__Classe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EFCoreToDo.Models.Classs

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Classes</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ClasssId" />

     


        <div class="form-group">
            <label asp-for="NbreEtudiants" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NbreEtudiants" class="form-control" />
                <span asp-validation-for="NbreEtudiants" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Speciality" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Speciality" class="form-control" />
                <span asp-validation-for="Speciality" class="text-danger"></span>
            </div>
        </div>



        <div class="form-group">
            <label asp-for="ClasseName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ClasseName" class="form-control" />
                <span asp-validation-for="ClasseName" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <label asp-for="Level" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Level" class="form-control" />
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/EFCoreToDo/Views/Class/Index.cshtml
@{
    ViewBag.Title = "La Liste des Classes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<EFCoreToDo.Models.Classs>


<!-- Bootstrap core CSS -->
<link href="~/css/bootstrap.min.css" rel="stylesheet">
<link href="~/css/bootstrap-reset.css" rel="stylesheet">

<!--Animation css-->
<link href="~/css/animate.css" rel="stylesheet">

<!--Icon-fonts css-->
<link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link href="~/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
<link href="~/assets/material-design-iconic-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

<!--Morris Chart CSS -->
<link rel="stylesheet" href="~/assets/morris/morris.css">


<!-- Custom styles for this template -->
<link href="~/css/style.css" rel="stylesheet">
<link href="~/css/helper.css" rel="stylesheet">


<!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
<!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
<![endif]-->

<script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-62751496-1', 'auto');
          ga('send', 'pageview');

</script>



@foreach (var item in Model)
{



    <div class="col-sm-6">
        <div class="panel">
            <div class="panel-body">
                <div class="media-main">
                    <a class="pull-left" href="#">
                        <img class="thumb-lg img-circle bx-s" src="~/img/esprit.jpg" alt="">
                    </a>
                    <div class="pull-right btn-group-sm">
                        
                    </div>
                    <div class="info">
                        <h4>@Html.DisplayFor(modelItem => item.ClasseName)</h4>
                        <hr>
                        <p class="text-muted">
                            Level : @Html.DisplayFor(modelItem => item.Level)
                            <hr>Speciality :
                            @Html.DisplayFor(modelItem => item.Speciality)
                            <hr>Stundents Number :
                            @Html.DisplayFor(modelItem => item.NbreEtudiants)

                        </p>
                    </div>
                </div>
                <div class="clearfix"></div>
                <hr>
                <ul class="social-links list-inline p-b-10">
                    <li>
                        <a asp-action="Edit" asp-route-id="@item.ClasssId">Edit</a>



                    </li>
                    <li> <a asp-action="Delete" asp-route-id="@item.ClasssId">Delete</a> </li>
                </ul>
            </div> <!-- panel-body -->
        </div> <!-- panel -->
    </div>
}

<!-- js placed at the end of the document so the pages load faster -->
<script src="~/js/jquery.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/pace.min.js"></script>
<script src="~/js/wow.min.js"></script>
<script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>


<script src="~/js/jquery.app.js"></script>				